---
title: "Movie Industry Analysis"
author: "Riley Adams, Jordan Bowman, Tracy Yu, Constanza Widel, Ruqayyah Siddique"
date: "5/29/2022"
output: html_document
---
```{r, echo = FALSE, warning = FALSE, message = FALSE}
# Libraries
require(dplyr)
require(ggplot2)
require(GGally)
require(lmtest)
require(car)
```

```{r, echo = FALSE}
movies_original <- read.csv("movies.csv")
dim(movies_original)

# Remove rows containing NA
movies <- movies_original[rowSums(is.na(movies_original)) == 0,]

# Create "month" using "released"
# A factor 1:12, indicating month of release
month <- numeric()

for (i in 1:length(movies$released)){
  if (grepl("January", movies$released[i])){
    month[i] <- 1
  }else if (grepl("February", movies$released[i])){
    month[i] <- 2
  }else if (grepl("March", movies$released[i])){
    month[i] <- 3
  }else if (grepl("April", movies$released[i])){
    month[i] <- 4
  }else if (grepl("May", movies$released[i])){
    month[i] <- 5
  }else if (grepl("June", movies$released[i])){
    month[i] <- 6
  }else if (grepl("July", movies$released[i])){
    month[i] <- 7
  }else if (grepl("August", movies$released[i])){
    month[i] <- 8
  }else if (grepl("September", movies$released[i])){
    month[i] <- 9
  }else if (grepl("October", movies$released[i])){
    month[i] <- 10
  }else if (grepl("November", movies$released[i])){
    month[i] <- 11
  }else{
    month[i] <- 12
  }
}

movies <- cbind(movies, month)
movies$month <- as.factor(movies$month)

# Here we can see almost 80% of the movies are from the US
# Considering IMDb is a US-based database, isolate to the US only
# sum(movies$country == "United States")/dim(movies)[1]
movies <- movies[movies$country == "United States",]

# remove variable we will not be using
drops <- c("released","director","writer","star","company")
movies <- movies[, !(names(movies) %in% drops)]
rownames(movies) <- 1:nrow(movies)
  
# Reorganize columns
organized <- c("name", "rating", "runtime", "genre", "month", "year", "votes", "score", "budget", "gross")
movies <- movies[, organized]

# Create variable for gross/budget
return_prop <-  movies$gross / movies$budget
movies <- cbind(movies, return_prop)

# All movies with blank rating were rated R
for (i in 1:nrow(movies)){
  if(movies$rating[i] == "")
    movies$rating[i] <- "R"
}

# Combine "Unrated" to "Not Rated" -> "Unrated"
for (i in 1:nrow(movies)){
  if(movies$rating[i] == "Not Rated")
    movies$rating[i] <- "Unrated"
}
```

```{r, echo = FALSE}
ggpairs(movies[,-1])
```
```{r, echo=FALSE}
hist(movies$budget, labels = TRUE,breaks = 18)
#cut at bin before 1.0e+08
mov_hist <- hist(movies$budget, labels = TRUE,breaks = 18)
budget_cat <- character()
for(i in 1:nrow(movies)){
  if (movies$budget[i] > mov_hist$breaks[5]){
    budget_cat[i] <- "high"
  }else{
    budget_cat[i] <- "low"
  }
}
movies <- cbind(movies, budget_cat)
# run average release year, check overall distribution of year
# check average score between two groups
```

```{r, echo = FALSE}
movies_num <- movies[unlist(lapply(movies, is.numeric))]
movies_num <- movies_num[-2]
cor(movies_num)
```

```{r}
# Responding to Q1
ggpairs(movies[c("score", "votes")])
# From chart we see that the correlation is extremely significant. 
var(movies$votes)
# From above note extremely high variability
densityPlot(log(movies$votes))

ggpairs(data.frame(movies$score, log(movies$votes)))
```

```{r, echo = FALSE}
lm_num <- lm(score ~ ., data = movies_num)
summary(lm_num)
vif(lm_num)
```

```{r}
model1 <- lm(formula = score ~ rating + runtime + genre + month + year + votes + budget + gross + return_prop , data = movies)
summary(model1)
```

While some levels of the variable categorical *genre* are deemed significant predictors of *score* (e.g. *drama*, *animation*), the majority have very high p-values and are not deemed significant predictors (e.g. *thriller*, *mystery*). *Month* is not a significant predictor, nor *gross*, nor *return_prop*.

```{r}
model2 <- lm(formula = score ~ rating + runtime + year + votes + budget , data = movies)
summary(model2)
```






